name: attend
description: Attendance managment system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS icons
  cupertino_icons: ^1.0.2

  # provider pattern
  provider: ^6.0.2

  # http client
  dio: ^4.0.4

  # secure storage
  flutter_secure_storage: ^5.0.2

  # json web tokens decoder
  jwt_decoder: ^2.0.1

  # json serialize/deserialize
  json_serializable: ^6.1.5

  # internationalization library
  intl: ^0.17.0

  # date/time picker
  flutter_datetime_picker: ^1.5.1

  # duration picker
  duration_picker: ^1.1.0+1

  # qr codes
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700